<a href="https://colab.research.google.com/github/minmincg/house_pricing_analysis/blob/main/Notebooks/neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#Import the csv by using the raw link
hpricing_df = pd.read_csv("https://raw.githubusercontent.com/minmincg/house_pricing_analysis/24b41d230570324f8d64a1326bcc9e9972a62608/Resources/austin_housing_reduced.csv")
hpricing_df.head()

,city,streetAddress,zipcode,latitude,longitude,propertyTaxRate,garageSpaces,hasCooling,hasGarage,hasHeating,...,numOfWaterfrontFeatures,numOfWindowFeatures,numOfCommunityFeatures,lotSizeSqFt,livingAreaSqFt,avgSchoolRating,numOfBathrooms,numOfBedrooms,numOfStories,numOfSchools
0,pflugerville,14424 Lake Victor Dr,78660,30.430632,-97.663078,1.98,2,True,True,True,...,0,1,0,6011.0,2601,2.666667,3.0,4,2,3
1,pflugerville,1104 Strickling Dr,78660,30.432672,-97.661697,1.98,2,True,True,True,...,0,0,0,6185.0,1768,2.666667,2.0,4,1,3
2,pflugerville,1408 Fort Dessau Rd,78660,30.409748,-97.639771,1.98,0,True,False,True,...,0,0,0,7840.0,1478,3.000000,2.0,3,1,4
3,pflugerville,1025 Strickling Dr,78660,30.432112,-97.661659,1.98,2,True,True,True,...,0,0,0,6098.0,1678,2.666667,2.0,3,1,3
4,pflugerville,15005 Donna Jane Loop,78660,30.437368,-97.656860,1.98,0,True,False,True,...,0,0,0,6708.0,2132,4.000000,3.0,3,2,3

In [2]:
# Determine the number of unique values in each column.
hpricing_df.nunique()

city                              9
streetAddress                 15000
zipcode                          48
latitude                      14269
longitude                     12379
propertyTaxRate                   3
garageSpaces                     14
hasCooling                        2
hasGarage                         2
hasHeating                        2
hasSpa                            2
hasView                           2
homeType                         10
yearBuilt                       115
latestPrice                    2338
numPriceChanges                  22
numOfAccessibilityFeatures        8
numOfAppliances                  13
numOfParkingFeatures              7
numOfPatioAndPorchFeatures        9
numOfSecurityFeatures             7
numOfWaterfrontFeatures           3
numOfWindowFeatures               5
numOfCommunityFeatures            9
lotSizeSqFt                    1403
livingAreaSqFt                 3616
avgSchoolRating                  27
numOfBathrooms                   16
numOfBedrooms                     9
numOfStories                      4
numOfSchools                      5
dtype: int64

In [3]:
# Drop the non-beneficial ID columns, 'city' and 'streetAddress'.
hpricing_df = hpricing_df.drop(columns = ['city', 'streetAddress','homeType'], axis=1)
hpricing_df.head()

,zipcode,latitude,longitude,propertyTaxRate,garageSpaces,hasCooling,hasGarage,hasHeating,hasSpa,hasView,...,numOfWaterfrontFeatures,numOfWindowFeatures,numOfCommunityFeatures,lotSizeSqFt,livingAreaSqFt,avgSchoolRating,numOfBathrooms,numOfBedrooms,numOfStories,numOfSchools
0,78660,30.430632,-97.663078,1.98,2,True,True,True,False,False,...,0,1,0,6011.0,2601,2.666667,3.0,4,2,3
1,78660,30.432672,-97.661697,1.98,2,True,True,True,False,False,...,0,0,0,6185.0,1768,2.666667,2.0,4,1,3
2,78660,30.409748,-97.639771,1.98,0,True,False,True,False,False,...,0,0,0,7840.0,1478,3.000000,2.0,3,1,4
3,78660,30.432112,-97.661659,1.98,2,True,True,True,False,False,...,0,0,0,6098.0,1678,2.666667,2.0,3,1,3
4,78660,30.437368,-97.656860,1.98,0,True,False,True,False,False,...,0,0,0,6708.0,2132,4.000000,3.0,3,2,3

In [4]:
# Making sure the columns got dropped
hpricing_df.columns

Index(['zipcode', 'latitude', 'longitude', 'propertyTaxRate', 'garageSpaces',
       'hasCooling', 'hasGarage', 'hasHeating', 'hasSpa', 'hasView',
       'yearBuilt', 'latestPrice', 'numPriceChanges',
       'numOfAccessibilityFeatures', 'numOfAppliances', 'numOfParkingFeatures',
       'numOfPatioAndPorchFeatures', 'numOfSecurityFeatures',
       'numOfWaterfrontFeatures', 'numOfWindowFeatures',
       'numOfCommunityFeatures', 'lotSizeSqFt', 'livingAreaSqFt',
       'avgSchoolRating', 'numOfBathrooms', 'numOfBedrooms', 'numOfStories',
       'numOfSchools'],
      dtype='object')

In [5]:
# Look at 'zipcode' value counts for binning
zip_counts = hpricing_df["zipcode"].value_counts()
zip_counts

78748    1137
78745    1025
78749     772
78704     693
78737     611
78739     603
78732     590
78759     559
78723     554
78757     518
78717     515
78731     487
78744     469
78753     438
78727     414
78758     393
78754     393
78702     382
78747     381
78750     321
78729     317
78735     308
78703     294
78721     244
78730     243
78728     224
78724     223
78741     217
78733     202
78746     190
78726     178
78751     172
78725     162
78736     162
78752     151
78756     137
78722      96
78617      85
78705      64
78660      36
78619      12
78734       9
78701       8
78719       5
78742       4
78652       4
78653       4
78738       1
Name: zipcode, dtype: int64

In [6]:
# Chose a cutoff value of less than 200 and create a list of application types to be replaced

zipcodes_to_replace = list(zip_counts[zip_counts<200].index)

# Replace in dataframe
for zip in zipcodes_to_replace:
    hpricing_df['zipcode'] = hpricing_df['zipcode'].replace(zip,"Other")

# Making sure the binning was successful
hpricing_df['zipcode'].value_counts()

Other    1480
78748    1137
78745    1025
78749     772
78704     693
78737     611
78739     603
78732     590
78759     559
78723     554
78757     518
78717     515
78731     487
78744     469
78753     438
78727     414
78754     393
78758     393
78702     382
78747     381
78750     321
78729     317
78735     308
78703     294
78721     244
78730     243
78728     224
78724     223
78741     217
78733     202
Name: zipcode, dtype: int64

In [7]:
#price_counts = hpricing_df.latestPrice.value_counts()
#price_counts

In [8]:
#Check data types
hpricing_df.dtypes

zipcode                        object
latitude                      float64
longitude                     float64
propertyTaxRate               float64
garageSpaces                    int64
hasCooling                       bool
hasGarage                        bool
hasHeating                       bool
hasSpa                           bool
hasView                          bool
yearBuilt                       int64
latestPrice                     int64
numPriceChanges                 int64
numOfAccessibilityFeatures      int64
numOfAppliances                 int64
numOfParkingFeatures            int64
numOfPatioAndPorchFeatures      int64
numOfSecurityFeatures           int64
numOfWaterfrontFeatures         int64
numOfWindowFeatures             int64
numOfCommunityFeatures          int64
lotSizeSqFt                   float64
livingAreaSqFt                  int64
avgSchoolRating               float64
numOfBathrooms                float64
numOfBedrooms                   int64
numOfStories                    int64
numOfSchools                    int64
dtype: object

In [9]:
#Convert zipcode to dummies because it is a categorical
#Didnt use dummies in the rest of the data (hasCooling, hasGarage, hasHeating, hasSpa, hasView, homeType) because it was already numerical
hpricing_df = pd.get_dummies(hpricing_df,dtype=float)
hpricing_df

#hpricing_df['zipcode']= hpricing_df['zipcode'].astype(float)
#hpricing_df.dtypes

,latitude,longitude,propertyTaxRate,garageSpaces,hasCooling,hasGarage,hasHeating,hasSpa,hasView,yearBuilt,...,zipcode_78747,zipcode_78748,zipcode_78749,zipcode_78750,zipcode_78753,zipcode_78754,zipcode_78757,zipcode_78758,zipcode_78759,zipcode_Other
0,30.430632,-97.663078,1.98,2,True,True,True,False,False,2012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,30.432672,-97.661697,1.98,2,True,True,True,False,False,2013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,30.409748,-97.639771,1.98,0,True,False,True,False,False,2018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,30.432112,-97.661659,1.98,2,True,True,True,False,False,2013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,30.437368,-97.656860,1.98,0,True,False,True,False,False,2002,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15002,30.161997,-97.816345,1.98,6,True,True,True,False,True,1986,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15003,30.240223,-97.772835,1.98,2,True,True,True,True,True,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15004,30.244835,-97.761124,1.98,2,True,True,True,False,False,1936,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15005,30.281569,-97.717789,1.98,0,True,False,True,False,False,1968,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15006,30.276930,-97.701523,1.98,1,True,True,True,False,True,1955,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
hpricing_df.columns

Index(['latitude', 'longitude', 'propertyTaxRate', 'garageSpaces',
       'hasCooling', 'hasGarage', 'hasHeating', 'hasSpa', 'hasView',
       'yearBuilt', 'latestPrice', 'numPriceChanges',
       'numOfAccessibilityFeatures', 'numOfAppliances', 'numOfParkingFeatures',
       'numOfPatioAndPorchFeatures', 'numOfSecurityFeatures',
       'numOfWaterfrontFeatures', 'numOfWindowFeatures',
       'numOfCommunityFeatures', 'lotSizeSqFt', 'livingAreaSqFt',
       'avgSchoolRating', 'numOfBathrooms', 'numOfBedrooms', 'numOfStories',
       'numOfSchools', 'zipcode_78702', 'zipcode_78703', 'zipcode_78704',
       'zipcode_78717', 'zipcode_78721', 'zipcode_78723', 'zipcode_78724',
       'zipcode_78727', 'zipcode_78728', 'zipcode_78729', 'zipcode_78730',
       'zipcode_78731', 'zipcode_78732', 'zipcode_78733', 'zipcode_78735',
       'zipcode_78737', 'zipcode_78739', 'zipcode_78741', 'zipcode_78744',
       'zipcode_78745', 'zipcode_78747', 'zipcode_78748', 'zipcode_78749',
       'zipcode_78750', 'zipcode_78753', 'zipcode_78754', 'zipcode_78757',
       'zipcode_78758', 'zipcode_78759', 'zipcode_Other'],
      dtype='object')

In [10]:
# Split our preprocessed data into our features and target arrays
y= hpricing_df['latestPrice'].values

X= hpricing_df.drop ('latestPrice', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4560

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 7,021
Trainable params: 7,021
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
#mae = mean absolute error & mse = mean squared error
nn.compile(loss="mse", optimizer="adam", metrics=["mae", "mse"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
352/352 [==============================] - 2s 2ms/step - loss: 418558738432.0000 - mae: 508161.4688 - mse: 418558738432.0000
Epoch 2/100
352/352 [==============================] - 1s 3ms/step - loss: 410294779904.0000 - mae: 502830.0312 - mse: 410294779904.0000
Epoch 3/100
352/352 [==============================] - 2s 6ms/step - loss: 380901949440.0000 - mae: 483084.0000 - mse: 380901949440.0000
Epoch 4/100
352/352 [==============================] - 2s 5ms/step - loss: 328790343680.0000 - mae: 445257.3438 - mse: 328790343680.0000
Epoch 5/100
352/352 [==============================] - 2s 4ms/step - loss: 266607558656.0000 - mae: 391784.1250 - mse: 266607558656.0000
Epoch 6/100
352/352 [==============================] - 1s 4ms/step - loss: 211703496704.0000 - mae: 340807.2500 - mse: 211703496704.0000
Epoch 7/100
352/352 [==============================] - 2s 5ms/step - loss: 173351190528.0000 - mae: 307816.6875 - mse: 173351190528.0000
Epoch 8/100
352/352 [==============================] - 2s 5ms/step - loss: 149892874240.0000 - mae: 288047.7500 - mse: 149892874240.0000
Epoch 9/100
352/352 [==============================] - 2s 4ms/step - loss: 133903605760.0000 - mae: 272363.2188 - mse: 133903605760.0000
Epoch 10/100
352/352 [==============================] - 1s 3ms/step - loss: 121267249152.0000 - mae: 256926.9375 - mse: 121267249152.0000
Epoch 11/100
352/352 [==============================] - 1s 4ms/step - loss: 110397284352.0000 - mae: 240846.2031 - mse: 110397284352.0000
Epoch 12/100
352/352 [==============================] - 3s 7ms/step - loss: 100972208128.0000 - mae: 225659.8281 - mse: 100972208128.0000
Epoch 13/100
352/352 [==============================] - 3s 7ms/step - loss: 92977995776.0000 - mae: 210858.3438 - mse: 92977995776.0000
Epoch 14/100
352/352 [==============================] - 2s 5ms/step - loss: 86423363584.0000 - mae: 198796.4375 - mse: 86423363584.0000
Epoch 15/100
352/352 [==============================] - 2s 4ms/step - loss: 81088905216.0000 - mae: 186620.5000 - mse: 81088905216.0000
Epoch 16/100
352/352 [==============================] - 1s 4ms/step - loss: 76743442432.0000 - mae: 176456.6562 - mse: 76743442432.0000
Epoch 17/100
352/352 [==============================] - 1s 4ms/step - loss: 73243475968.0000 - mae: 167947.3281 - mse: 73243475968.0000
Epoch 18/100
352/352 [==============================] - 2s 4ms/step - loss: 70454632448.0000 - mae: 160741.6406 - mse: 70454632448.0000
Epoch 19/100
352/352 [==============================] - 2s 5ms/step - loss: 68190507008.0000 - mae: 154030.2656 - mse: 68190507008.0000
Epoch 20/100
352/352 [==============================] - 1s 3ms/step - loss: 66335207424.0000 - mae: 149192.5312 - mse: 66335207424.0000
Epoch 21/100
352/352 [==============================] - 1s 3ms/step - loss: 64774746112.0000 - mae: 145544.4688 - mse: 64774746112.0000
Epoch 22/100
352/352 [==============================] - 1s 3ms/step - loss: 63468625920.0000 - mae: 142239.4531 - mse: 63468625920.0000
Epoch 23/100
352/352 [==============================] - 1s 2ms/step - loss: 62339375104.0000 - mae: 139449.4688 - mse: 62339375104.0000
Epoch 24/100
352/352 [==============================] - 1s 2ms/step - loss: 61345918976.0000 - mae: 137272.4375 - mse: 61345918976.0000
Epoch 25/100
352/352 [==============================] - 1s 2ms/step - loss: 60456087552.0000 - mae: 135160.1250 - mse: 60456087552.0000
Epoch 26/100
352/352 [==============================] - 1s 2ms/step - loss: 59679461376.0000 - mae: 134141.0625 - mse: 59679461376.0000
Epoch 27/100
352/352 [==============================] - 1s 2ms/step - loss: 58957615104.0000 - mae: 132436.2500 - mse: 58957615104.0000
Epoch 28/100
352/352 [==============================] - 1s 2ms/step - loss: 58309685248.0000 - mae: 130802.2812 - mse: 58309685248.0000
Epoch 29/100
352/352 [==============================] - 1s 2ms/step - loss: 57703997440.0000 - mae: 129984.1953 - mse: 57703997440.0000
Epoch 30/100
352/352 [==============================] - 1s 2ms/step - loss: 57125916672.0000 - mae: 129344.8438 - mse: 57125916672.0000
Epoch 31/100
352/352 [==============================] - 1s 2ms/step - loss: 56584441856.0000 - mae: 127649.8438 - mse: 56584441856.0000
Epoch 32/100
352/352 [==============================] - 1s 2ms/step - loss: 56086552576.0000 - mae: 126762.1719 - mse: 56086552576.0000
Epoch 33/100
352/352 [==============================] - 1s 2ms/step - loss: 55600394240.0000 - mae: 125976.8750 - mse: 55600394240.0000
Epoch 34/100
352/352 [==============================] - 1s 2ms/step - loss: 55162527744.0000 - mae: 125330.5156 - mse: 55162527744.0000
Epoch 35/100
352/352 [==============================] - 1s 2ms/step - loss: 54731304960.0000 - mae: 124332.7891 - mse: 54731304960.0000
Epoch 36/100
352/352 [==============================] - 1s 3ms/step - loss: 54331437056.0000 - mae: 123605.2812 - mse: 54331437056.0000
Epoch 37/100
352/352 [==============================] - 1s 3ms/step - loss: 53978382336.0000 - mae: 122991.9844 - mse: 53978382336.0000
Epoch 38/100
352/352 [==============================] - 1s 3ms/step - loss: 53619134464.0000 - mae: 122538.2812 - mse: 53619134464.0000
Epoch 39/100
352/352 [==============================] - 1s 2ms/step - loss: 53278851072.0000 - mae: 121706.0938 - mse: 53278851072.0000
Epoch 40/100
352/352 [==============================] - 1s 2ms/step - loss: 52956348416.0000 - mae: 120937.9688 - mse: 52956348416.0000
Epoch 41/100
352/352 [==============================] - 1s 2ms/step - loss: 52667830272.0000 - mae: 120826.8359 - mse: 52667830272.0000
Epoch 42/100
352/352 [==============================] - 1s 2ms/step - loss: 52379181056.0000 - mae: 120107.5469 - mse: 52379181056.0000
Epoch 43/100
352/352 [==============================] - 1s 2ms/step - loss: 52095164416.0000 - mae: 119527.3984 - mse: 52095164416.0000
Epoch 44/100
352/352 [==============================] - 1s 2ms/step - loss: 51838803968.0000 - mae: 119528.3438 - mse: 51838803968.0000
Epoch 45/100
352/352 [==============================] - 1s 2ms/step - loss: 51577720832.0000 - mae: 118720.3672 - mse: 51577720832.0000
Epoch 46/100
352/352 [==============================] - 1s 2ms/step - loss: 51343413248.0000 - mae: 118304.4375 - mse: 51343413248.0000
Epoch 47/100
352/352 [==============================] - 1s 2ms/step - loss: 51116503040.0000 - mae: 118267.4141 - mse: 51116503040.0000
Epoch 48/100
352/352 [==============================] - 1s 2ms/step - loss: 50889506816.0000 - mae: 117524.7812 - mse: 50889506816.0000
Epoch 49/100
352/352 [==============================] - 1s 2ms/step - loss: 50690220032.0000 - mae: 117385.0547 - mse: 50690220032.0000
Epoch 50/100
352/352 [==============================] - 1s 2ms/step - loss: 50471059456.0000 - mae: 117303.3750 - mse: 50471059456.0000
Epoch 51/100
352/352 [==============================] - 1s 2ms/step - loss: 50280361984.0000 - mae: 116648.4375 - mse: 50280361984.0000
Epoch 52/100
352/352 [==============================] - 1s 2ms/step - loss: 50107396096.0000 - mae: 116618.4297 - mse: 50107396096.0000
Epoch 53/100
352/352 [==============================] - 1s 3ms/step - loss: 49910738944.0000 - mae: 116432.8359 - mse: 49910738944.0000
Epoch 54/100
352/352 [==============================] - 1s 3ms/step - loss: 49746984960.0000 - mae: 115967.5312 - mse: 49746984960.0000
Epoch 55/100
352/352 [==============================] - 1s 3ms/step - loss: 49574424576.0000 - mae: 115887.0938 - mse: 49574424576.0000
Epoch 56/100
352/352 [==============================] - 1s 2ms/step - loss: 49402191872.0000 - mae: 115867.8516 - mse: 49402191872.0000
Epoch 57/100
352/352 [==============================] - 1s 2ms/step - loss: 49281081344.0000 - mae: 115218.8203 - mse: 49281081344.0000
Epoch 58/100
352/352 [==============================] - 1s 2ms/step - loss: 49132445696.0000 - mae: 114949.0625 - mse: 49132445696.0000
Epoch 59/100
352/352 [==============================] - 1s 2ms/step - loss: 48981618688.0000 - mae: 114813.8047 - mse: 48981618688.0000
Epoch 60/100
352/352 [==============================] - 1s 2ms/step - loss: 48830763008.0000 - mae: 114660.6953 - mse: 48830763008.0000
Epoch 61/100
352/352 [==============================] - 1s 2ms/step - loss: 48707051520.0000 - mae: 114484.1562 - mse: 48707051520.0000
Epoch 62/100
352/352 [==============================] - 1s 2ms/step - loss: 48564113408.0000 - mae: 114125.0391 - mse: 48564113408.0000
Epoch 63/100
352/352 [==============================] - 1s 2ms/step - loss: 48465784832.0000 - mae: 114364.6172 - mse: 48465784832.0000
Epoch 64/100
352/352 [==============================] - 1s 2ms/step - loss: 48326172672.0000 - mae: 113929.3281 - mse: 48326172672.0000
Epoch 65/100
352/352 [==============================] - 1s 2ms/step - loss: 48203325440.0000 - mae: 113850.2969 - mse: 48203325440.0000
Epoch 66/100
352/352 [==============================] - 1s 2ms/step - loss: 48071692288.0000 - mae: 113262.0859 - mse: 48071692288.0000
Epoch 67/100
352/352 [==============================] - 1s 2ms/step - loss: 47980081152.0000 - mae: 113321.3750 - mse: 47980081152.0000
Epoch 68/100
352/352 [==============================] - 1s 2ms/step - loss: 47862013952.0000 - mae: 113416.6875 - mse: 47862013952.0000
Epoch 69/100
352/352 [==============================] - 1s 3ms/step - loss: 47755411456.0000 - mae: 113096.2734 - mse: 47755411456.0000
Epoch 70/100
352/352 [==============================] - 1s 3ms/step - loss: 47620427776.0000 - mae: 112565.3828 - mse: 47620427776.0000
Epoch 71/100
352/352 [==============================] - 1s 3ms/step - loss: 47539871744.0000 - mae: 113147.4766 - mse: 47539871744.0000
Epoch 72/100
352/352 [==============================] - 1s 3ms/step - loss: 47437119488.0000 - mae: 112683.8516 - mse: 47437119488.0000
Epoch 73/100
352/352 [==============================] - 1s 2ms/step - loss: 47348604928.0000 - mae: 112451.3047 - mse: 47348604928.0000
Epoch 74/100
352/352 [==============================] - 1s 2ms/step - loss: 47236513792.0000 - mae: 112219.9062 - mse: 47236513792.0000
Epoch 75/100
352/352 [==============================] - 1s 2ms/step - loss: 47140564992.0000 - mae: 112278.0781 - mse: 47140564992.0000
Epoch 76/100
352/352 [==============================] - 1s 2ms/step - loss: 47038947328.0000 - mae: 112048.7188 - mse: 47038947328.0000
Epoch 77/100
352/352 [==============================] - 1s 2ms/step - loss: 46967902208.0000 - mae: 112126.9844 - mse: 46967902208.0000
Epoch 78/100
352/352 [==============================] - 1s 2ms/step - loss: 46850990080.0000 - mae: 111652.0391 - mse: 46850990080.0000
Epoch 79/100
352/352 [==============================] - 1s 2ms/step - loss: 46772088832.0000 - mae: 111676.0391 - mse: 46772088832.0000
Epoch 80/100
352/352 [==============================] - 1s 2ms/step - loss: 46677934080.0000 - mae: 111499.0234 - mse: 46677934080.0000
Epoch 81/100
352/352 [==============================] - 1s 2ms/step - loss: 46572134400.0000 - mae: 111424.7422 - mse: 46572134400.0000
Epoch 82/100
352/352 [==============================] - 1s 2ms/step - loss: 46502363136.0000 - mae: 111170.8906 - mse: 46502363136.0000
Epoch 83/100
352/352 [==============================] - 1s 2ms/step - loss: 46405292032.0000 - mae: 111120.1172 - mse: 46405292032.0000
Epoch 84/100
352/352 [==============================] - 1s 2ms/step - loss: 46310916096.0000 - mae: 111008.5234 - mse: 46310916096.0000
Epoch 85/100
352/352 [==============================] - 1s 4ms/step - loss: 46227660800.0000 - mae: 110984.3359 - mse: 46227660800.0000
Epoch 86/100
352/352 [==============================] - 1s 3ms/step - loss: 46150397952.0000 - mae: 110612.8594 - mse: 46150397952.0000
Epoch 87/100
352/352 [==============================] - 1s 3ms/step - loss: 46060793856.0000 - mae: 110659.1250 - mse: 46060793856.0000
Epoch 88/100
352/352 [==============================] - 1s 2ms/step - loss: 45978177536.0000 - mae: 110526.3906 - mse: 45978177536.0000
Epoch 89/100
352/352 [==============================] - 1s 2ms/step - loss: 45902647296.0000 - mae: 110214.2578 - mse: 45902647296.0000
Epoch 90/100
352/352 [==============================] - 1s 2ms/step - loss: 45813772288.0000 - mae: 110327.3828 - mse: 45813772288.0000
Epoch 91/100
352/352 [==============================] - 1s 2ms/step - loss: 45740580864.0000 - mae: 109847.5312 - mse: 45740580864.0000
Epoch 92/100
352/352 [==============================] - 1s 2ms/step - loss: 45661069312.0000 - mae: 109935.8359 - mse: 45661069312.0000
Epoch 93/100
352/352 [==============================] - 1s 2ms/step - loss: 45580447744.0000 - mae: 109748.1875 - mse: 45580447744.0000
Epoch 94/100
352/352 [==============================] - 1s 2ms/step - loss: 45520826368.0000 - mae: 109475.1953 - mse: 45520826368.0000
Epoch 95/100
352/352 [==============================] - 1s 2ms/step - loss: 45448462336.0000 - mae: 109586.8438 - mse: 45448462336.0000
Epoch 96/100
352/352 [==============================] - 1s 2ms/step - loss: 45366333440.0000 - mae: 109664.9609 - mse: 45366333440.0000
Epoch 97/100
352/352 [==============================] - 1s 2ms/step - loss: 45280727040.0000 - mae: 109494.4297 - mse: 45280727040.0000
Epoch 98/100
352/352 [==============================] - 1s 2ms/step - loss: 45227085824.0000 - mae: 109081.7969 - mse: 45227085824.0000
Epoch 99/100
352/352 [==============================] - 1s 2ms/step - loss: 45156880384.0000 - mae: 108685.7734 - mse: 45156880384.0000
Epoch 100/100
352/352 [==============================] - 1s 3ms/step - loss: 45120233472.0000 - mae: 108952.0625 - mse: 45120233472.0000

In [15]:
# Evaluate the model using the test data
errors = nn.evaluate(X_test_scaled,y_test,verbose=2)
errors
print(f"MSE: {errors [0]}, MAE: {errors[1]}")

118/118 - 0s - loss: 39863054336.0000 - mae: 107120.2188 - mse: 39863054336.0000 - 299ms/epoch - 3ms/step
MSE: 39863054336.0, MAE: 107120.21875

In [33]:
nn.predict([X_train_scaled.tolist()[1]])

1/1 [==============================] - 0s 68ms/step

array([[587789.25]], dtype=float32)

In [43]:
# Export our model to HDF5 file
from google.colab import files
nn.save("neural_network.h5")
files.download("neural_network.h5")

In [ ]:
# Export standardScaler from sklearn to file
from joblib import dump, load
dump(scaler, 'std_scaler.bin', compress=True)
files.download("std_scaler.bin")